### ISSUE TITLE
SecTrustedApplicationCreateFromPath is deprecated (Big Sur compatibility?)

### ISSUE THREAD

**Issue by synfinatic** [synfinatic/onelogin-aws-role#19]
This was actually [fixed in go-keychain](https://github.com/keybase/go-keychain/issues/54) but looking in the tickets against 99designs/keyring it's not clear what they plan to do.  Seems like they just pinned to an older version of go-keychain which is not Big Sur compatible. :-/

```
# github.com/keybase/go-keychain
cgo-gcc-prolog:203:11: warning: 'SecTrustedApplicationCreateFromPath' is deprecated: first deprecated in macOS 10.15 - No longer supported [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Security.framework/Headers/SecTrustedApplication.h:59:10: note: 'SecTrustedApplicationCreateFromPath' has been explicitly marked deprecated here
```

**Comment by mtibben** [comment]
@synfinatic if you wish to help resolve the issue see https://github.com/99designs/keyring/issues/66#issuecomment-712425649
